# Generated by Django 5.0.1 on 2024-03-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_huellas_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='huellas',
            name='caso',
            field=models.IntegerField(null=True),
        ),
    ]
