# Generated by Django 5.0.1 on 2024-04-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_casos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='huellas',
            table='fingerprints',
        ),
    ]
