# Generated by Django 5.0.1 on 2024-04-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_rename_ap_materno_personas_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casos',
            old_name='codigo_caso',
            new_name='case_code',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='nombre_caso',
            new_name='case_name',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='departamento',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='perito',
            new_name='expert',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='id_caso',
            new_name='id_case',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='activate',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='f_modificacion',
            new_name='registration_date',
        ),
        migrations.RenameField(
            model_name='casos',
            old_name='sospechosos',
            new_name='suspects',
        ),
        migrations.RemoveField(
            model_name='casos',
            name='f_registro',
        ),
        migrations.AddField(
            model_name='casos',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
