# Generated by Django 5.0.1 on 2024-04-24 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_rename_codigo_caso_casos_case_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='implicado',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='fecha_nacimiento',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='lugar_nacimiento',
            new_name='birth_place',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='caso',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='apellido_materno',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='color_pelo',
            new_name='hair_color',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='altura_m',
            new_name='height_m',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='id_implicado',
            new_name='id_involved',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='carnet_identidad',
            new_name='identity_card',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='color_piel',
            new_name='issued_in',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='apellido_paterno',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='nombres',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='expedido_en',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='ocupacion',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='f_registro',
            new_name='registration_date',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='nacionalidad',
            new_name='skin_color',
        ),
        migrations.RenameField(
            model_name='implicado',
            old_name='peso_kg',
            new_name='weight_kg',
        ),
    ]
