# Generated by Django 5.0.1 on 2024-04-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_remove_implicado_foto_anular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implicado',
            name='fecha_nacimiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
