# Generated by Django 5.0.1 on 2024-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_huellas_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implicado',
            name='carnet_identidad',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
