# Generated by Django 5.0.1 on 2024-04-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_implicado_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personas',
            table='experts',
        ),
    ]
