# Generated by Django 5.0.1 on 2024-07-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_alter_implicado_carnet_identidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='implicado',
            name='sexo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
