# Generated by Django 5.0.1 on 2024-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_implicado_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='tipo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
