# Generated by Django 5.0.1 on 2024-03-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_huellas_caso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='perito',
            field=models.IntegerField(null=True),
        ),
    ]
