# Generated by Django 5.0.1 on 2024-04-24 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_remove_implicado_foto_anular_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casos',
            table='cases',
        ),
    ]
