# Generated by Django 5.0.1 on 2024-04-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_huellas_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='implicado',
            table='involved',
        ),
    ]
